### ISSUE TITLE
Problem with Wagtail 1.4

### ISSUE THREAD

**Issue by SalahAdDin** [bashu/wagtail-embedvideos#28]
Hi, again, i'm testing Wagtail 1.4 and i have the next problem when i try add a new video:
![templatedoesnotexist at -admin-embed_videos-add- - chromium_049](https://cloud.githubusercontent.com/assets/5034215/13734213/bb1c2280-e969-11e5-8ffa-272e324e26bf.png)
![templatedoesnotexist at -admin-embed_videos-add- - chromium_050](https://cloud.githubusercontent.com/assets/5034215/13734214/bb1ef424-e969-11e5-9e53-63bd610d2863.png)
Here are the traceback:

``` bash
Internal Server Error: /admin/embed_videos/add/
Traceback (most recent call last):
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/engine.py", line 169, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: wagtailadmin/shared/tag_field_css.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/wagtail/wagtailadmin/decorators.py", line 22, in decorated_view
    return view_func(request, *args, **kwargs)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/wagtail_embed_videos/views/embed_videos.py", line 173, in add
    'form': form,
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/backends/django.py", line 97, in render
    reraise(exc, self.backend)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/backends/django.py", line 107, in reraise
    six.reraise(exc.__class__, new, sys.exc_info()[2])
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/backends/django.py", line 95, in render
    return self.template.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 206, in render
    return self._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 197, in _render
    return self.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 992, in render
    bit = node.render_annotated(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/base.py", line 959, in render_annotated
    return self.render(context)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/loader_tags.py", line 200, in render
    template = context.template.engine.get_template(template_name)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/engine.py", line 190, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/run/media/salahaddin/Datos/Proyectos/Trabajo/adkm/lib/python3.5/site-packages/django/template/engine.py", line 169, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: wagtailadmin/shared/tag_field_css.html
[13/Mar/2016 21:55:42] "GET /admin/embed_videos/add/ HTTP/1.1" 500 558978
```

What's the problem?

**Comment by SalahAdDin** [comment]
Seems that delete these inexistent templates solve the problem. I don't know why.

No, doesn't solve it, and wich better support, now Wagtail doesn't need django-compressor, so, you should be delete compress tag.

**Comment by SalahAdDin** [comment]
Ok, i fixed it, seemsly, and i'll do a PR with this and with a few locale files.

Ok, this will fix this problem: https://github.com/infoportugal/wagtail-embedvideos/pull/29
