### ISSUE TITLE
Error with 'SearchForm' when updating to Wagtail 2.5

### ISSUE THREAD

**Issue by iokouts** [bashu/wagtail-embedvideos#70]
I tried to update from Wagtail 2.4 to 2.5 and got the following error:

```
Traceback (most recent call last):
  File ".\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "venv\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "venv\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "venv\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "venv\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "venv\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "venv\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "venv\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "venv\lib\site-packages\django\urls\resolvers.py", line 398, in check
    for pattern in self.url_patterns:
  File "venv\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "venv\lib\site-packages\django\urls\resolvers.py", line 571, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "venv\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "venv\lib\site-packages\django\urls\resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "venv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "KickIt\urls.py", line 5, in <module>
    from wagtail.admin import urls as wagtailadmin_urls
  File "venv\lib\site-packages\wagtail\admin\urls\__init__.py", line 13, in <module>
    from wagtail.admin.api import urls as api_urls
  File "venv\lib\site-packages\wagtail\admin\api\urls.py", line 11, in <module>
    for fn in hooks.get_hooks('construct_admin_api'):
  File "venv\lib\site-packages\wagtail\core\hooks.py", line 47, in get_hooks
    search_for_hooks()
  File "venv\lib\site-packages\wagtail\core\hooks.py", line 41, in search_for_hooks
    list(get_app_submodules('wagtail_hooks'))
  File "venv\lib\site-packages\wagtail\utils\apps.py", line 23, in get_app_submodules
    yield name, import_module('%s.%s' % (name, submodule_name))
  File "venv\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "venv\lib\site-packages\wagtail_embed_videos\wagtail_hooks.py", line 12, in <module>
    from wagtail_embed_videos import admin_urls
  File "venv\lib\site-packages\wagtail_embed_videos\admin_urls.py", line 3, in <module>
    from wagtail_embed_videos.views import embed_videos, chooser
  File "venv\lib\site-packages\wagtail_embed_videos\views\embed_videos.py", line 12, in <module>
    from wagtail.admin.forms import SearchForm
ImportError: cannot import name 'SearchForm' from 'wagtail.admin.forms' (venv\lib\site-packages\wagtail\admin\forms\__init__.py)
```

**Comment by dkirkham** [comment]
I had the same problem although that was going from wagtail 2.6.2 to 2.7.1 (perhaps some deprecations were finally removed?).

There turns out to be multiple import and other problems, but the PR by @akrs3 at #67 seems to fix them all - and it seems to run ok in both 2.6.2 and 2.7.1.

I have a site in development and will report if anything in @akrs3's PR/branch misbehaves. (And thanks @akrs3 !)

**Comment by DiogoMarques29** [comment]
With the introduction of Embedded Content in wagtail 1.12 https://docs.wagtail.io/en/v1.12.6/releases/1.12.html#improved-embed-configuration, this package will no longer be maintained.
